apiVersion: 1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: duong1997/udagram-api-user:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws"
              readOnly: true
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
